// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import {
  Noto_Serif_Hebrew,
  Frank_Ruhl_Libre,
  David_Libre,
} from "next/font/google";
import "./globals.css";

const notoSerifHebrew = Noto_Serif_Hebrew({
  subsets: ["hebrew"],
  weight: ["400", "700"], // regular and bold
  variable: "--font-noto-serif-hebrew",
  display: "swap",
});

const frankRuhlLibreHebrew = Frank_Ruhl_Libre({
  subsets: ["hebrew"],
  weight: ["400", "700"], // regular and bold
  variable: "--font-frank-ruhl-libre",
  display: "swap",
});

const davidLibreHebrew = David_Libre({
  subsets: ["hebrew"],
  weight: ["400", "700"], // regular and bold
  variable: "--font-david-libre",
  display: "swap",
});

export const metadata = {
  title: "Brasserie Omnia",
  description: "A classy brasserie experience",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      dir="rtl"
      className={`${notoSerifHebrew.variable} ${frankRuhlLibreHebrew.variable} ${davidLibreHebrew.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
